# Generated by Django 2.2.1 on 2019-07-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_friend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friend',
            table='friend',
        ),
    ]
